version: "3.7"

services:
  goservice:
    image: go_auth:dev
    container_name: go_auth
    ports:
      - "8081:8080"
    networks:
      - go_net
  nginx:
    image: go_nginx:dev
    container_name: go_nginx
    ports:
      - "80:80"
    depends_on:
      - "goservice"
    networks:
      - go_net
  go_postgres:
    container_name: go_postgres
    image: postgres:16.0
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-test}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      PGDATA: /data/postgres
      POSTGRES_DB: ${POSTGRES_DB:-test}
    volumes:
      - go_postgres_db:/data/postgres
    ports:
      - "5864:5432"
    networks:
      - go_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
  redis-master:
    image: redis:latest
    container_name: redis-master
    command: [
      "redis-server",
      "--appendonly", "yes",
      "--requirepass", "${REDIS_PASSWORD:-myStrongPassword}",
      "--databases", "${REDIS_DATABASES:-16}"
    ]
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-myStrongPassword}", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - go_net

  redis-replica-1:
    image: redis:latest
    container_name: redis-replica-1
    command: [
      "redis-server",
      "--replicaof", "redis-master", "6379",
      "--masterauth", "${REDIS_PASSWORD:-myStrongPassword}",
      "--requirepass", "${REDIS_PASSWORD:-myStrongPassword}",
      "--databases", "${REDIS_DATABASES:-16}"
    ]
    depends_on:
      - redis-master
    networks:
      - go_net

  redis-replica-2:
    image: redis:latest
    container_name: redis-replica-2
    command: [
      "redis-server",
      "--replicaof", "redis-master", "6379",
      "--masterauth", "${REDIS_PASSWORD:-myStrongPassword}",
      "--requirepass", "${REDIS_PASSWORD:-myStrongPassword}",
      "--databases", "${REDIS_DATABASES:-16}"
    ]
    depends_on:
      - redis-master
    networks:
      - go_net

  redis-replica-3:
    image: redis:latest
    container_name: redis-replica-3
    command: [
      "redis-server",
      "--replicaof", "redis-master", "6379",
      "--masterauth", "${REDIS_PASSWORD:-myStrongPassword}",
      "--requirepass", "${REDIS_PASSWORD:-myStrongPassword}",
      "--databases", "${REDIS_DATABASES:-16}"
    ]
    depends_on:
      - redis-master
    networks:
      - go_net

  redis-replica-4:
    image: redis:latest
    container_name: redis-replica-4
    command: [
      "redis-server",
      "--replicaof", "redis-master", "6379",
      "--masterauth", "${REDIS_PASSWORD:-myStrongPassword}",
      "--requirepass","${REDIS_PASSWORD:-myStrongPassword}",
      "--databases", "${REDIS_DATABASES:-16}"
    ]
    depends_on:
      - redis-master
    networks:
      - go_net

volumes:
  go_postgres_db:

networks:
  go_net:
    driver: bridge
